DROP TABLE IF EXISTS grades;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS groups;

CREATE TABLE groups(
id SERIAL PRIMARY KEY,
name VARCHAR(50)
);



CREATE TABLE teachers(
id SERIAL PRIMARY KEY,
fullname VARCHAR(50)
);



CREATE TABLE subjects(
id SERIAL PRIMARY KEY,
name VARCHAR(50),
teacher_id INTEGER REFERENCES teachers(id)
	ON DELETE CASCADE
);



CREATE TABLE students(
id SERIAL PRIMARY KEY,
fullname VARCHAR(150),
group_id INTEGER REFERENCES groups(id)
	ON DELETE CASCADE
);



CREATE TABLE grades(
id SERIAL PRIMARY KEY,
students_id INTEGER REFERENCES students(id)
	ON DELETE CASCADE,
subject_id INTEGER REFERENCES subjects(id)
	ON DELETE CASCADE,
grade VARCHAR(10),
grade_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
