version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: YBessonov
    ports:
      - "5432:5432"  # Открываем порт для подключения
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные между перезапусками

volumes:
  postgres_data:
